### ISSUE TITLE
String-backed enums

### ISSUE THREAD

**Issue by AlexanderAllen** [AlexanderAllen/panettone#46]
Sourcing the following OAS example:

```yaml
OAuthToken:
  type: object
  properties:
    grant_type:
      type: string
      description: One of `authorization_code`, `client_credentials`, `refresh_token`
      example: authorization_code
      enum:
        - authorization_code
        - refresh_token
        - client_credentials
```
Results in:

```php
# OAuthToken.php
class OAuthToken
{
    /** One of `authorization_code`, `client_credentials`, `refresh_token` */
    public ?GrantType $grantType = null;

...

# GrantType.php
enum GrantType
{
    case AuthorizationCode;
    case RefreshToken;
    case ClientCredentials;
}

```

The emitted `GrantType` is [PHP-CS (PER)](https://www.php-fig.org/per/coding-style/#9-enumerations) compliant, which is nice.

However, the data coming down from the pipe is going to contain the literal values listed in the OAS source (`authorization_code`, `client_credentials`, etc.), and therefore the resulting PHP enum is going to need a string backing to store those literal string values.
